Merge To Main
abdallahmalima/Financial-Statements pull request #7
Opened 2023-01-05 15:40 UTC by abdallahmalima

In this milestone I:
- Create a Basic structure and install dependencies for react and redux
- Create Components for Financial Statements and Income statements
- Create a slice for  Financial Statements and Income statements
- Create thunk for Call API for Financial Statements and Income statements
- Add Test for Financial Statements and Income statements

2023-01-05 17:35 UTC, MeqdamAlqudah requested changes
Hi @abdallahmalima , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.webp?cid=ecf05e47gwng0hbyexib5lsg6ipiozrgzgkvmcv7x2qz37nx&rid=giphy.webp&ct=g)

## Highlights
:+1: use of redux
:+1: design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 17:35 UTC, MeqdamAlqudah commented on README.md
> +<!-- TABLE OF CONTENTS -->
- [ ] Please record a video presenting the features of the project.

2023-01-05 17:35 UTC, MeqdamAlqudah commented on README.md
> +
- [ ] Please give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-01-06 08:02 UTC, rloterh commented on README.md
> +
well resolved! ✔️

2023-01-06 08:33 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Antony,  

Your project is complete! 🏁 Awesome job! 🥇 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Nice presentation of this project!
- Good job acknowledging Nelson Sakwa on Behance for the [Original design idea](https://www.behance.net/sakwadesignstudio)!
- API fetch properly implemented!
- State management with Redux properly implemented!
- Navigation working as intended!
- Filter works great!
- Good ReadMe!

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

_Kindly consider my inline comments marked **[OPTIONAL]** under this review_

**You can also consider:**
- You used incorrect git-flow/ GitHub flow for this project. Kindly note that capstone project worked on by a single contributor should have merge request flow **from feature into development**. Kindly note this important step for subsequent projects.
 
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 08:33 UTC, rloterh commented on src/index.css
> +
- [ ] OPTIONAL
The styling of the list on your Homepage does not conform to the alternating dual-color pattern of the provided [design template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)). Kindly note we as much as possible want your design to match the provided [template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)). Therefore kindly ensure that the cells/ card of your list follow the **alternating dual-color pattern**. Each cell of the list item should have surrounding cells having **different (alternating) background color(s)**.

**Your design:**        |  **The original design:**
:-------------------------:|:-------------------------:
<img width="800" alt="Home Page" src="https://user-images.githubusercontent.com/12745474/210959542-47fd9961-549a-45d0-b7f7-29ad094d1a19.png"> | <img width="800" alt="Home Page" src="https://user-images.githubusercontent.com/12745474/142270463-4d16b9d3-7557-430c-80eb-a7c40589a4a6.png">

2023-01-06 08:33 UTC, rloterh commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] OPTIONAL
The provided MIT license link in your ReadMe is invalid, kindly endeavor to fix it, and remove the guide note below it.

2023-01-06 10:30 UTC, merged